config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/show'
  devise_for :users
  root to: 'farms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get '/farms_layout', to: 'pages#farms_layout'
  get '/dashboard_layout', to: 'pages#dashboard_layout'
  get '/farms/:id/count_clap', to: 'farms#count_clap'

  resources :farms do
    resources :chatrooms, only: [:create]
    resources :claps, only: [ :create ]
    resources :scorings, only: [ :create ]
    resources :likes, only: [ :create ]
  end
  
  # resources :users, only: [ :show, :edit ] do
  #   resources :lists
  # end

  resource :user, only: [ :update ] do 
      get :profile
      get :messages
      resources :lists, only: [ :index, :show ]
      resources :shops, only: [ :create ]
  end 

  resources :chatrooms, only: [:index, :show, :destroy] do 
    resources :messages, only: [ :create ]
  end

  resources :shops, only: [ :show, :edit ]
  resources :likes, only: [ :destroy ]
  resources :lists, only: [ :create, :destroy ]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :criterions, dependent: :destroy
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  belongs_to :farm
  has_many :messages, dependent: :destroy
end

app/models/clap.rb
class Clap < ApplicationRecord
  belongs_to :user
  belongs_to :farm
end

app/models/criterion.rb
class Criterion < ApplicationRecord
  belongs_to :category
end

app/models/farm.rb
class Farm < ApplicationRecord
  acts_as_taggable_on :tags
  belongs_to :user
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :chatrooms
  has_many :claps, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :scorings, dependent: :destroy

  def average(scope)
    notes = []
    Scoring.where(criterion_id: Criterion.where(category_id: Category.find_by(name: scope)), farm_id: self.id).each do |critere|
      notes << critere.score
    end
    notes.sum / notes.count
  end

  def total
    scores = []
    Scoring.where(farm_id: self.id).each do |note| 
      scores << note.score
    end
    scores.sum / scores.count
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :list
  belongs_to :farm
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :shop
  has_many :likes, dependent: :destroy
  has_many :farms, through: :likes
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/scoring.rb
class Scoring < ApplicationRecord
  belongs_to :criterion
  belongs_to :farm
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :shops, dependent: :destroy
  has_many :claps, dependent: :destroy
  has_many :messages
  
end

app/controllers/claps_controller.rb
class ClapsController < ApplicationController

  def create
    @farm = Farm.find(params[:farm_id])
    authorize @farm
    @user = current_user
    authorize @user
    @clap = Clap.new
    @clap.user = @user
    @clap.farm = @farm
    @clap.save
    render json: {
      clap_count: @farm.claps.count
    }
  end
  
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    @tags = ['Elevage', 'Grandes Cultures', 'Maraîchage', 'Viticulture', 'Arboriculture']
    @farms = policy_scope(Farm).geocoded
    
    if params[:tag].present?
      @farms = policy_scope(Farm).geocoded.tagged_with(params[:tag], any: true)
    else
      @farms = policy_scope(Farm).geocoded
    end

    @markers = @farms.map do |farm|
      {
        lat: farm.latitude,
        lng: farm.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { farm: farm }),
        image_url: helpers.asset_url('farmer.png')
      }
    end
  end

  def show
    @farm = Farm.find(params[:id])
    authorize @farm
    @chatroom = Chatroom.new
    @list = List.new
    @clap = Clap.new
    if current_user != nil
      @shop = Shop.where(user_id: current_user.id).first
      @wish_lists = List.where(shop_id: Shop.where(user_id: current_user.id))
    end
  end

  def count_clap
    skip_authorization
    @claps = Clap.where(farm_id: params[:id]).count
    respond_to do |format|
      format.json { render json: { clapsCount: @claps } }
     end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @farm = Farm.find(params[:farm_id])
    authorize @farm
    @list = List.find(params[:params_list])
    authorize @list
    @like = Like.new

    @like.farm_id = @farm.id
    @like.list_id = @list.id
    if @like.save
      flash[:notice] = "La ferme a été ajoutée à votre liste"
      redirect_to user_lists_path
    else
      render :new
    end
  end

  def destroy
    @like = Like.find(params[:id])
    authorize @like
    @like.destroy
    flash[:notice] = "La ferme a été supprimée de votre liste"
    redirect_to user_lists_path
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    skip_authorization
    @user = current_user
    @lists = policy_scope(List).where(shop_id: Shop.where(user_id: current_user.id))
  end

  def create
    skip_authorization
    @shop = Shop.where(user_id: current_user.id).first
    #authorize @shop
    @list = List.new(list_params)
    @list.shop = @shop
    if @list.save
      flash[:notice] = "Votre liste a été créée"
      redirect_to user_lists_path
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    authorize @list
    @list.destroy
    redirect_to user_lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save  
        ChatroomChannel.broadcast_to(
          @chatroom,
          render_to_string(partial: "message", locals: { message: @message, user: current_user })
        )
      redirect_to chatroom_path(@chatroom, anchor: "message-#{@message.id}")
    else
      render "chatrooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
  def dashboard_layout
  end

  def farms_layout
  end 


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def show
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params.merge(user: current_user))
    authorize @shop
    if @shop.save
      flash[:notice] = "Votre magasin a été créé"
      redirect_to profile_user_path
    else
      render :new
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = current_user
    authorize @user
    @shops = Shop.where(user: current_user.id)
    @shop = Shop.new
  end  

  def update
    skip_authorization
    current_user.update(user_params)
    redirect_to profile_user_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/farms/_add_to_list.html.erb
<div class="dropdown ml-3">
  <a class="btn btn-success text-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Ajoutez à votre liste
  </a>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
  <% @wish_lists.each do |list| %>
    <%= link_to list.name, farm_likes_path(@farm, params_list: list), class: "dropdown-item", method: :post %>
  <% end %>
    <!-- Button trigger modal -->
    <a href="#" type="button" class="btn btn-primary dropdown-item" data-toggle="modal" data-target="#listmodal">Créer une nouvelle liste</a>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="listmodal" tabindex="-1" role="dialog" aria-labelledby="listmodalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-body">
      <div class="modal-header">
        <h5 class="modal-title" id="listmodalLabel">Créez une nouvelle liste</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@list) do |f| %>
          <%= f.input :name, placeholder: "Mes fournisseurs" %>
          <%= f.submit "Sauvegarder", class: "btn btn-success text-white my-2" %>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/farms/_info_window.html.erb
<div class="farm-card text-white text-center">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span class='text-white mr-1'>&times;</span>
  </button>
  <div class='text-left p-3'>
    <h3><%= farm.name %></h3>
    <h6><%= farm.address %></h6>
  </div>
  <div class="text-center py-3">
    <% if farm.photos.attached? %>
      <%= cl_image_tag farm.photos.first.key, height: 200, width:300, style: "width: 90%", crop: :fill, class: 'rounded' %>
    <% else %>
      <%= image_tag "https://images.unsplash.com/photo-1444858291040-58f756a3bdd6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1530&q=80", height: 200, width:300, style: "width: 90%", crop: :fill, class: 'rounded' %>
    <% end %>  
  </div>
  <div class="text-center px-3 pt-3 pb-0 d-flex">
    <% farm.tags.each do |tag| %>
      <h6 class=' border p-2 mr-2 rounded'> <%=tag %></h6>
    <% end %>
  </div>
  <div class="farm-infos text-white text-center">
    <div class="sc-gauge-card text-center">
      <div class="sc-background-card mb-3">
        <div class="sc-percentage-card" style="transform: rotate(<%= farm.total * 1.8 %>deg);"></div>
        <div class="sc-mask-card"></div>
        <h2 class="sc-value-card"><%= farm.total %> %</h2>
      </div>
    </div>
    <h6>Score de durabilité</h6>
    <div class='text-center py-3' id="button-card">
      <%= link_to "Voir cette ferme", farm_path(farm), class: "btn btn-success text-white", data: { turbolinks: 'false' } %>
    </div>
  </div>
</div>

app/views/farms/index.html.erb
<div class="bg-primary px-2 pb-5 pt-5">
  <div class="container">
    <div class="banner-home row justify-content-between">
        <div class="search col-6">
          <h2 class='text-white my-5'>Trouvez un producteur en accord avec vos valeurs</h2>
          <%= simple_form_for :search, url: farms_path + '#map', method: :get do |f| %>

            <div class="search-form-control form-group">
              <input class="border border-success form-control string required" type="text" name="query" id="search_query" placeholder='Saisissez un lieu de recherche' />
            </div>

            <h5 class='text-white mt-4 mb-3'>Quel type de produit cherchez-vous ?</h5>


              <div class="row m-auto mb-3 justify-content-start btn-group-toggle align-items-center" data-toggle="buttons">
                <% @tags.each do |tag| %>
                  <label class="btn text-white border rounded py-2 text-center mb-2 mr-2" for="<%=tag%>">
                    <input type="checkbox" name="tag[]" data-toggle="button" id="<%=tag%>" value="<%=tag%>">
                    <p class='m-0'><%= tag %></p>
                   </label>
               <% end %>
              </div>

              <%# <button type="button" class="btn btn-outline-success bg-white col-2">
                <i class="fas fa-carrot"></i>
                <p class="mb-0">Légumes</p>
              </button>
              <button type="button" class="btn btn-outline-success bg-white col-2">
                <i class="fas fa-apple-alt"></i>
                <p class="mb-0">Fruits</p>
              </button>
              <button type="button" class="btn btn-outline-success bg-white col-2">
                <i class="fas fa-drumstick-bite"></i>
                <p class="mb-0">Viande</p>
              </button>
              <button type="button" class="btn btn-outline-success bg-white col-2">
                <i class="fas fa-ice-cream"></i>
                <p class="mb-0">Crèmerie</p>
              </button>
              <button type="button" class="btn btn-outline-success bg-white col-2">
                <i class="fas fa-wine-bottle"></i>
                <p class="mb-0">Vin</p>
              </button> %>

              <button type="submit" class="btn btn-success text-white my-4">
                <h5 class="m-2"><i class="fas fa-search"></i> Voir les producteurs</h5>
              </button>
          <% end %>
        </div>
        <div class='col-6 justify-content-center'>
          <%= image_tag "market-detoured.png", style: "width: 100%", class: 'illustration' %>
        </div>
    </div>    
  </div>
</div>

<div id="map"
    style="width: 100%; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    data-latitude="<%= Geocoder.search(params[:query]).first.latitude if (!params[:query].nil? && params[:query]!="") %>"
    data-longitude="<%= Geocoder.search(params[:query]).first.longitude if (!params[:query].nil? && params[:query]!="") %>"></div>

<div class="bg-info px-2 py-5">
  <div class="container py-5">
    <div class="d-flex">
      <div class='col-6 pr-3'>
        <%= image_tag "Hero-removebg-preview.png", style: "width: 100%", class: 'illustration' %>
      </div>
      <div class='col-6 pl-5 justify-content-end'>
        <h1 class='text-primary'><strong>Nous évaluons,</strong></h1>
        <h1 class='text-primary'><strong>Vous pilotez!</strong></h1>
        <h5 class='text-warning mt-4'>Collaborer avec des agriculteurs engagés n'a jamais été aussi facile pour leurs partenaires.</h5>
      </div>
    </div>
  </div>
</div>

app/views/farms/show.html.erb
<% content_for :meta_title, "#{@farm.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @farm.description %>
<%# <% content_for :meta_image, cl_image_path(@farm.photos.first.path) %>

<div class="bg-primary text-white">
  <div class="pt-5 pb-3 container">
    <div class="row no-gutters flex-md-row">
      <div class="col-8 pr-5">
        <div class="d-flex">
          <h2><%= @farm.name %></h2>
          <a href="https://<%= @farm.url %>" target="_blank" class="text-white btn"><i class="fas fa-link"></i></a>
        </div>
        <div class="m-0 d-flex">
          <% @farm.tags.each do |tag| %>
            <p class='mr-2 text-white border rounded py-2 text-center px-2'> <%=tag %></p>
          <% end %>
        </div>
        <div class="card-text">
          <p class="m-0"><%= @farm.description %></p>
        </div>
        <div class="d-flex mt-4">
          <% if current_user != nil %>
          <%= render 'claps' %>
            <%= render 'add_to_list' %>
            <%= simple_form_for [@farm, @chatroom]  do |f|  %>
              <%= f.submit 'Lancer la discussion', class: 'ml-3 btn btn-success text-white' %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div id="carouselExampleControls" class="carousel slide col-4" data-ride="carousel">
        <div class="carousel-inner">
          <% if @farm.photos.attached? %>
            <% @farm.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= 'active' if index == 0 %>">
                <%= cl_image_tag photo.key, height: 200, width:300, style: "width: 100%", crop: :fill, class: 'rounded-sm' %>
              </div>
            <% end %>
          <% else %>
            <%= image_tag "https://images.unsplash.com/photo-1444858291040-58f756a3bdd6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1530&q=80", height: 200, width:300, style: "width: 100%", crop: :fill, class: 'rounded-sm' %>
          <% end %>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
          </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
    <div>
      <h3 class="mt-5">Résultats d'évaluation</h3>
    </div>
  </div>
  <div class="container d-flex mt-5">
    <div class="sc-gauge text-center col-4">
      <div class="sc-background mb-3">
        <div class="sc-percentage" style="transform: rotate(<%= @farm.total * 1.8 %>deg);"></div>
        <div class="sc-mask"></div>
        <span class="sc-value">
          <%= @farm.total %>
          <h5 class="d-inline">%</h5>
        </span>
      </div>
      <h6 class="sc-indice">Score Global</h6>
    </div>
    <ul class="nav nav-tabs row col-8 pr-0" id="myTab" role="tablist">
      <li class="nav-item col-3">
        <a class="nav-link active" id="env-tab" data-toggle="tab" href="#env" role="tab" aria-controls="env" aria-selected="true">
          <div class="pt-3 px-3 text-center">
            <div class="h1 m-0">
              <%= @farm.average("Environnemental") %>
            </div>
            <div class="text-muted py-2">
              <i class="fab fa-envira"></i>
              <p class="m-0 d-flex justify-content-center">Environnement</p>
            </div>
          </div>
        </a>
      </li>
      <li class="nav-item col-3">
        <a class="nav-link" id="social-tab" data-toggle="tab" href="#social" role="tab" aria-controls="social" aria-selected="false">
          <div class="pt-3 px-3 text-center">
            <div class="h1 m-0">
              <%= @farm.average("Social") %>
            </div>
            <div class="text-muted py-2">
            <i class="fas fa-industry"></i>
            <p class="m-0 d-flex justify-content-center">Social</p>
            </div>
          </div>
        </a>
      </li>
      <li class="nav-item col-3">
        <a class="nav-link" id="eco-tab" data-toggle="tab" href="#eco" role="tab" aria-controls="eco" aria-selected="false">
        <div class="pt-3 px-3 text-center">
            <div class="h1 m-0">
              <%= @farm.average("Économique") %>
            </div>
            <div class="text-muted py-2">
              <i class="fas fa-euro-sign"></i>
              <p class="m-0 d-flex justify-content-center">Economie</p>
            </div>
          </div>
        </a>
      </li>
      <li class="nav-item col-3 pr-0">
        <a class="nav-link" id="globale-tab" data-toggle="tab" href="#globale" role="tab" aria-controls="globale" aria-selected="false">
          <div class="pt-3 px-3 text-center">
            <div class="h1 m-0">
              <%= @farm.average("Global") %>
            </div>
            <div class="text-muted py-2">
            <i class="fas fa-tractor"></i>    
            <p class="m-0 d-flex justify-content-center">Propriétés</p>
            </div>
          </div>
        </a>
      </li>
    </ul>
  </div>
</div>
<div class="container p-0">
  <div class="tab-content border border-top-0 rounded-bottom mb-5" id="myTabContent">
    <div class="tab-pane fade show active" id="env" role="tabpanel" aria-labelledby="env-tab">
      <%= render 'rating', zone: "Environnemental" %>
    </div>
    <div class="tab-pane fade" id="social" role="tabpanel" aria-labelledby="social-tab">
      <%= render 'rating', zone: "Social" %>
    </div>
    <div class="tab-pane fade" id="eco" role="tabpanel" aria-labelledby="eco-tab">
      <%= render 'rating', zone: "Économique" %>
    </div>
    <div class="tab-pane fade" id="globale" role="tabpanel" aria-labelledby="globale-tab">
        <%= render 'rating', zone: "Global" %>
    </div>
  </div>
</div>

<div class='text-center mb-5'>
  <%= link_to 'Retour aux fermes', farms_path, class: 'btn btn-success text-white m-5' %>
</div>

app/views/lists/_displayed_list.html.erb
<% @lists.each do |list| %>
<div id="<%= list.name %>" class="tabcontent">
  <h3 class="py-3 text-primary"><%= list.name %></h3>
  <div class="table-responsive border rounded bg-white mb-4 shadow-sm">
    <table class='table text-primary' data-controller='sort-table'>
      <thead>
        <tr>
          <th class="text-left w-25 align-middle"><h6><em>Ferme</em></h6></th>
          <th class="text-center w-25 px-0"><div data-id='1' data-action='click->sort-table#sort'><h5 class='m-0 btn btn-outline-primary' data-target='sort-table.global'><strong><em>Score</em></strong></h5> <i class="arrow fas fa-arrow-down"></i><i class="arrow d-none fas fa-arrow-up"></i></div></th>
          <th class="text-center w-10 px-0"><div data-id='2' data-action='click->sort-table#sort'><h6 class='m-0 btn btn-outline-primary' data-target='sort-table.env'><em>Environnement</em></h6> <i class="arrow d-none fas fa-arrow-down"></i><i class="arrow d-none fas fa-arrow-up"></i></div></th>
          <th class="text-center w-10 px-0"><div data-id='3' data-action='click->sort-table#sort'><h6 class='m-0 btn btn-outline-primary' data-target='sort-table.social'><em>Social</em></h6> <i class="arrow d-none fas fa-arrow-down"></i><i class="arrow d-none fas fa-arrow-up"></i></div></th>
          <th class="text-center w-10 px-0"><div data-id='4' data-action='click->sort-table#sort'><h6 class='m-0 btn btn-outline-primary' data-target='sort-table.eco'><em>Economie</em></h6> <i class="arrow d-none fas fa-arrow-down"></i><i class="arrow d-none fas fa-arrow-up"></i></div></th>
          <th class="text-center w-10 px-0"><div data-id='5' data-action='click->sort-table#sort'><h6 class='m-0 btn btn-outline-primary' data-target='sort-table.propriete'><em>Propriétés</em></h6> <i class="arrow d-none fas fa-arrow-down"></i><i class="arrow d-none fas fa-arrow-up"></i></div></th>
        </tr>
      </thead>
      <tbody class='my-4 border-bottom' data-target='sort-table.body' data-ordering='descending'>
        <% list.farms.sort_by { |farm| -farm.total }.each do |farm| %>
        <tr>
          <td class="w-25 py-4">
            <%= link_to like_path(farm.likes.find_by(list: list)), method: :delete, remote: true do %>
              <i class="fas fa-minus-circle"></i>
            <% end %>
            <%= link_to "#{farm.name}", farm_path(farm), class: 'text-center text-decoration-none p-2 bg-success text-white rounded'%>
          </td>
          <td class="text-center w-25 py-4"><strong><h5><%= farm.total %> %</h5></strong></td>
          <td class="text-center w-10 py-4"><%= farm.average("Global") %> %</td>
          <td class="text-center w-10 py-4"><%= farm.average("Social") %> %</td>
          <td class="text-center w-10 py-4"><%= farm.average("Économique") %> %</td>
          <td class="text-center w-10 py-4"><%= farm.average("Environnemental") %> %</td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>

app/views/lists/_my_lists.html.erb
<div class='d-flex my-3'>
  <% @lists.each do |list| %>
    <div class="d-flex shadow-sm btn border rounded bg-white col-3 mr-2 text-left p-0">
      <a id='list' class="tablinks listTrigger col-10 py-3" data-target="<%= list.name%>" >
        <h5 class='text-primary'><%= list.name %></h5>
        <div class="d-flex justify-content-between">
          <%# <p class='text-warning m-0'><em><%= list.shop.address</em></p> %>
          <div class='text-success'>
            <% if list.private %>
              <i class="fas fa-eye-slash"></i>
            <% else %>
              <i class="fas fa-eye"></i>
            <% end %>
          </div>
        </div>
      </a>
      <div class="col-2 float-right">
        <%= link_to list_path(list), method: :delete, remote: true do %>
          <span class="btn py-0">×</span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<%# <div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th></th>
        <th>Nom</th>
        <th>Boutique</th>
        <th>Visibilité</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @lists.each do |list| %>
        <%# <tr>
          <td class="text-center">
            <a class="tablinks listTrigger" data-target="<%= list.name"> %>
              <%# <i class="btn-sm btn-outline-success fas fa-plus"></i>
            </a>
          </td>
          <%# <td><%= list.name %>
          <%# <td><%= Shop.find(list.shop_id).address %>
          <%# <td><%= list.private ? "private" : "public"%>
          <%# <td> %>
            <%# <%= link_to list_path(list), method: :delete, remote: true do %>
              <%# <i class="mr-2 fas fa-trash-alt"></i> %>
            <%# <% end %>
          <%# </td> %>
        <%# </tr> %>
      <%# <% end %>
    <%# </tbody>
  </table>
</div> %>

app/views/users/_shop_modal.html.erb
<div class="modal fade" id="shopmodal" tabindex="-1" role="dialog" aria-labelledby="shopmodalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-body">
      <div class="modal-header">
        <h5 class="modal-title" id="shopmodalLabel">Créez une nouvelle liste</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [ @user, @shop ] do |f| %>
          <%= f.input :address, placeholder: "Mon magasin" %>
          <%= f.submit "Sauvegarder", class: "btn btn-success text-white my-2" %>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<%# <%= link_to "Ajouter", user_shops_path(current_user), class: "btn btn-success text-white my-4", method: :post %>

app/views/users/profile.html.erb
<%= render 'shared/navbar_user' %>
<div class="container">
  <div class='m-5'>
    <%= render 'myprofile' %>
  </div>
</div>