config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/show'
  devise_for :users
  root to: 'farms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get '/farms_layout', to: 'pages#farms_layout'
  get '/dashboard_layout', to: 'pages#dashboard_layout'
  get '/farms/:id/count_clap', to: 'farms#count_clap'

  resources :farms do
    resources :chatrooms, only: [:create]
    resources :claps, only: [ :create ]
    resources :scorings, only: [ :create ]
    resources :likes, only: [ :create ]
  end
  
  # resources :users, only: [ :show, :edit ] do
  #   resources :lists
  # end

  resource :user, only: [ :update ] do 
      get :profile
      get :messages
      resources :lists, only: [ :index, :show ]
      resources :shops, only: [ :create ]
  end 

  resources :chatrooms, only: [:index, :show, :destroy] do 
    resources :messages, only: [ :create ]
  end

  resources :shops, only: [ :show, :edit ]
  resources :likes, only: [ :destroy ]
  resources :lists, only: [ :create, :destroy ]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :criterions, dependent: :destroy
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  belongs_to :farm
  has_many :messages, dependent: :destroy
end

app/models/clap.rb
class Clap < ApplicationRecord
  belongs_to :user
  belongs_to :farm
end

app/models/criterion.rb
class Criterion < ApplicationRecord
  belongs_to :category
end

app/models/farm.rb
class Farm < ApplicationRecord
  acts_as_taggable_on :tags
  belongs_to :user
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :chatrooms
  has_many :claps, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :scorings, dependent: :destroy

  def average(scope)
    notes = []
    Scoring.where(criterion_id: Criterion.where(category_id: Category.find_by(name: scope)), farm_id: self.id).each do |critere|
      notes << critere.score
    end
    notes.sum / notes.count
  end

  def total
    scores = []
    Scoring.where(farm_id: self.id).each do |note| 
      scores << note.score
    end
    scores.sum / scores.count
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :list
  belongs_to :farm
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :shop
  has_many :likes, dependent: :destroy
  has_many :farms, through: :likes
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/scoring.rb
class Scoring < ApplicationRecord
  belongs_to :criterion
  belongs_to :farm
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :shops, dependent: :destroy
  has_many :claps, dependent: :destroy
  has_many :messages
  
end

app/controllers/claps_controller.rb
class ClapsController < ApplicationController

  def create
    @farm = Farm.find(params[:farm_id])
    authorize @farm
    @user = current_user
    authorize @user
    @clap = Clap.new
    @clap.user = @user
    @clap.farm = @farm
    @clap.save
    render json: {
      clap_count: @farm.claps.count
    }
  end
  
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    @tags = ['Elevage', 'Grandes Cultures', 'Maraîchage', 'Viticulture', 'Arboriculture']
    @farms = policy_scope(Farm).geocoded
    
    if params[:tag].present?
      @farms = policy_scope(Farm).geocoded.tagged_with(params[:tag], any: true)
    else
      @farms = policy_scope(Farm).geocoded
    end

    @markers = @farms.map do |farm|
      {
        lat: farm.latitude,
        lng: farm.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { farm: farm }),
        image_url: helpers.asset_url('farmer.png')
      }
    end
  end

  def show
    @farm = Farm.find(params[:id])
    authorize @farm
    @chatroom = Chatroom.new
    @list = List.new
    @clap = Clap.new
    if current_user != nil
      @shop = Shop.where(user_id: current_user.id).first
      @wish_lists = List.where(shop_id: Shop.where(user_id: current_user.id))
    end
  end

  def count_clap
    skip_authorization
    @claps = Clap.where(farm_id: params[:id]).count
    respond_to do |format|
      format.json { render json: { clapsCount: @claps } }
     end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @farm = Farm.find(params[:farm_id])
    authorize @farm
    @list = List.find(params[:params_list])
    authorize @list
    @like = Like.new

    @like.farm_id = @farm.id
    @like.list_id = @list.id
    if @like.save
      flash[:notice] = "La ferme a été ajoutée à votre liste"
      redirect_to user_lists_path
    else
      render :new
    end
  end

  def destroy
    @like = Like.find(params[:id])
    authorize @like
    @like.destroy
    flash[:notice] = "La ferme a été supprimée de votre liste"
    redirect_to user_lists_path
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    skip_authorization
    @user = current_user
    @lists = policy_scope(List).where(shop_id: Shop.where(user_id: current_user.id))
  end

  def create
    skip_authorization
    @shop = Shop.where(user_id: current_user.id).first
    #authorize @shop
    @list = List.new(list_params)
    @list.shop = @shop
    if @list.save
      flash[:notice] = "Votre liste a été créée"
      redirect_to user_lists_path
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    authorize @list
    @list.destroy
    redirect_to user_lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
  def dashboard_layout
  end

  def farms_layout
  end 


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def show
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params.merge(user: current_user))
    authorize @shop
    if @shop.save
      flash[:notice] = "Votre magasin a été créé"
      redirect_to profile_user_path
    else
      render :new
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    
    <div class="container-body pt-5">
      <%= yield %>
    </div>
    
    <%= render 'shared/footer' %>

   </body>
</html>

app/views/pages/dashboard_layout.html.erb
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">
              <span data-feather="user"></span>
              My Profile <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="list"></span>
              My Lists
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="message-circle"></span>
              My Messages
            </a>
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">My Lists</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>Lorem</td>
              <td>ipsum</td>
              <td>dolor</td>
              <td>sit</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>amet</td>
              <td>consectetur</td>
              <td>adipiscing</td>
              <td>elit</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>Integer</td>
              <td>nec</td>
              <td>odio</td>
              <td>Praesent</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h3>My List : List 1</h3>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>Lorem</td>
              <td>ipsum</td>
              <td>dolor</td>
              <td>sit</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>amet</td>
              <td>consectetur</td>
              <td>adipiscing</td>
              <td>elit</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>Integer</td>
              <td>nec</td>
              <td>odio</td>
              <td>Praesent</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>libero</td>
              <td>Sed</td>
              <td>cursus</td>
              <td>ante</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>dapibus</td>
              <td>diam</td>
              <td>Sed</td>
              <td>nisi</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>Nulla</td>
              <td>quis</td>
              <td>sem</td>
              <td>at</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>nibh</td>
              <td>elementum</td>
              <td>imperdiet</td>
              <td>Duis</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>sagittis</td>
              <td>ipsum</td>
              <td>Praesent</td>
              <td>mauris</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>Fusce</td>
              <td>nec</td>
              <td>tellus</td>
              <td>sed</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>augue</td>
              <td>semper</td>
              <td>porta</td>
              <td>Mauris</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>massa</td>
              <td>Vestibulum</td>
              <td>lacinia</td>
              <td>arcu</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>eget</td>
              <td>nulla</td>
              <td>Class</td>
              <td>aptent</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>taciti</td>
              <td>sociosqu</td>
              <td>ad</td>
              <td>litora</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>torquent</td>
              <td>per</td>
              <td>conubia</td>
              <td>nostra</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>per</td>
              <td>inceptos</td>
              <td>himenaeos</td>
              <td>Curabitur</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>sodales</td>
              <td>ligula</td>
              <td>in</td>
              <td>libero</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="dashboard.js"></script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer pt-4 border-top">
  <div class="d-flex">
    <div class="col-4 text-center">
      <h5>Nos services</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Notations</a></li>
        <li><a class="text-muted" href="#">Conseils</a></li>
        <li><a class="text-muted" href="#">Interventions</a></li>
        <li><a class="text-muted" href="#">Audit</a></li>
        <li><a class="text-muted" href="#">Coaching</a></li>
      </ul>
    </div>
    <div class="col-4 text-center">
      <h5>Contactez-nous</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">support@ecofarms.com</a></li>
        <li><a class="text-muted" href="#">Aide & Support</a></li>
        <li><a class="text-muted" href="#">Ressources presse</a></li>
        <li><a class="text-muted" href="#">Nous rejoindre</a></li>
        <li><a class="text-muted" href="#">A propos de nous</a></li>
      </ul>
    </div>
    <div class="col-4 text-center pl-0">
      <h5>Retrouvez-nous</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">YouTube</a></li>
        <li><a class="text-muted" href="#">Twitter</a></li>
        <li><a class="text-muted" href="#">Facebook</a></li>
        <li><a class="text-muted" href="#">LinkedIn</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-primary fixed-top">
  <%= link_to root_path, class: "navbar-brand bg-transparent", data: { turbolinks: 'false' } do %>
    <div class='d-flex align-items-center'>
      <%= image_tag "ecofarms_logo.png" %>
      <h4 class='ml-2 mb-0'><strong><span class='text-white'>Eco</span><span class='text-success'>Farms</span></strong></h4>
    </div>
  <% end %>

  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, width: 40, height: 40, gravity: "faces", crop: "fill" %>
          <% else %>
            <%= image_tag "https://www.dts.edu/wp-content/uploads/sites/6/2018/04/Blank-Profile-Picture.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon Profil", profile_user_path, class: "dropdown-item text-primary" %>
            <%= link_to "Mes Listes", user_lists_path, class: "dropdown-item text-primary" %>
            <%= link_to "Mes Messages", chatrooms_path, class: "dropdown-item text-primary" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item text-primary" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link text-white btn" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_user.html.erb
<div class="nav d-flex justify-content-center navbar navbar-expand-sm navbar-light navbar-lewagon border-top border-bottom mt-3">
  <%= link_to profile_user_path, class: "menu-option nav-link" do %>
    <i class="far fa-user"></i>
      <span class="pl-3"> Mon Profil</span>
    <% end %>
    <%= link_to user_lists_path, class: "menu-option nav-link" do %>
      <i class="fas fa-list"></i>
    <span class="pl-3">Mes Listes</span>
    <% end %>
      <%= link_to chatrooms_path, class: "menu-option nav-link" do %>
        <i class="far fa-comment"></i>
      <span class="pl-3">Mes Messages</span>
    <% end %>
</div>

app/views/shared/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light collapse border-right pr-0">
  <div class="sidebar-sticky pt-3">
    <ul class="nav flex-column pl-3">
      <li>
        <%= link_to profile_user_path, class: "menu-option nav-link" do %>
          <i class="far fa-user"></i>
          <span class="pl-3"> Mon Profil</span>
        <% end %>
      </li>
      <li>
        <%= link_to user_lists_path, class: "menu-option nav-link" do %>
          <i class="fas fa-list"></i>
          <span class="pl-3">Mes Listes</span>
        <% end %>
      </li>
      <li>
        <%= link_to chatrooms_path, class: "menu-option nav-link" do %>
          <i class="far fa-comment"></i>
          <span class="pl-3">Mes Messages</span>
        <% end %>
    </ul>
  </div>
</nav>